export class Competition {
  RaceId: string,
  km: string,
  catId: string,
  DisciplineId: string,
  StatusId: number,
  StatusText: string,
  HasLiveData: boolean,
  IsLive: boolean,
  StartTime: string,
  Description: string,
  ShortDescription: string,
  Location: string,
  ResultsCredit: string,
  TimingCredit: string,
  HasAnalysis: boolean,
  StartMode: string,
  NrShootings: number,
  NrSpareRounds: number,
  HasSpareRounds: boolean,
  PenaltySeconds: number,
  NrLegs: number,
  ShootingPositions: string,
  LocalUTCOffset: number
}